config/routes.rb
Rails.application.routes.draw do
  # get 'ingredients/index'
  # get 'ingredients/show'
  # get 'ingredients/new'
  # get 'ingredients/create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cocktails do
    resources :doses, only: [:new, :create]
    end
  # get 'cocktails'

  # get 'cocktails/:id'

  # get 'cocktails/new'
  # post 'cocktails'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  validates :name, presence: true
  validates :name, uniqueness: true
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient, dependent: :destroy
  belongs_to :cocktail
  validates :description, presence: true
  validates_uniqueness_of :cocktail, :scope => [:ingredient]
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :doses
  has_many :cocktails, through: :doses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail =Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(strong_params)

    if @cocktail.save
      redirect_to cocktails_path, notice: "Cocktail has been added"
    else
      render :new
    end
  end

  def strong_params
    params.require(:cocktail).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktails/index.html.erb
<div class="container">
  <h1>Cocktails List</h1>
  <ul>
  <% @cocktails.each do |i|%>
  <li><%= link_to i.name, cocktail_path(i) %></li>
  <% end %>
  </ul>

<%= link_to 'Add a cocktail', new_cocktail_path %>
</div>

app/views/cocktails/new.html.erb
<div class="container">
  <h3>Enter Cocktail Name</h3>
  <%= simple_form_for(@cocktail) do |f|%>
  <p><%= f.input :name %></p>
  <%= f.submit "Create", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/cocktails/show.html.erb
<div class="container">

  <h1><%= @cocktail.name %></h1>
  <ul>
    <% @cocktail.doses.each do |dose|%>
    <%= dose.ingredient.name %>
    <li><%= dose.name %></li>
  </ul>
  <% end %>

  <%= link_to 'Go back to list', cocktails_path, class:'btn btn-primary' %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
  <%= javascript_pack_tag "application" %>
  </body>
</html>